import cv2
from picamera2 import Picamera2
from ultralytics import YOLO 

#Camera initialization
picam = Picamera2()
picam.preview_configuration.main.size = (1280, 720)
picam.preview_configuration.main.format = "RGB888"
picam.preview_configuration.align
picam.configure("preview")
picam.start

#Load Yolo11 machine vision model
yolo_model = YOLO("yolo11n.pt")

while True:
    #Single frame capture & scan
    frame = picam.capture_array()
    scan = yolo_model(frame)

    #Plot & show results generated by YOLO model
    frame_plot = scan[0].plot()
    cv2.imshow("PiCam", frame_plot)

    if(cv2.waitKey(1) == ord("q")):
        break

#Close all opened cv2 display windows
cv2.destroyAllWindows()